name: Python Package Workflow

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install twine uv

    - name: Build package
      run: |
        uv build

    - name: Publish package
      env:
        TWINE_USERNAME: "__token__"
        TWINE_PASSWORD: ${{ secrets.API_TOKEN }}
      run: |
        uv publish -u $TWINE_USERNAME -p $TWINE_PASSWORD